M48
; DRILL file {KiCad 9.0.7} date 2026-02-14T08:27:34+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-14T08:27:34+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C1.016
%
G90
G05
T1
X136.5Y-95.96
X136.5Y-101.04
T2
X129.335Y-97.23
X129.335Y-99.77
T3
X141.0Y-96.5
X141.0Y-101.0
X147.5Y-96.5
X147.5Y-101.0
T4
X156.518Y-98.0
X166.5Y-98.0
M30
